### ISSUE TITLE
It would be great to not rely on environment variables for auth

### ISSUE THREAD

**Issue by philmcmahon** [Mapistry/awsS3Promisified#1]
This library looks great, thanks!

I don't thing the AWS.config step in https://github.com/Mapistry/awsS3Promisified/blob/master/index.js should be necessary - from http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html

> Remember, if you set your AWS credentials in the shared credentials file or via environment variables, the AWS SDK for Node.js will automatically detect them, and you will not need to perform any manual credential configuration in your application.

**Comment by alliejanoch** [comment]
@philmcmahon - Thanks for checking out our little library! Good point, if you submit and pull request, I'll take a look and merge it.

**Comment by alliejanoch** [comment]
@philmcmahon - I finally got around to making this change: c5463209970e94c0fd2014e85293554259d6a6db

Thanks for the recommendation.

**Comment by philmcmahon** [comment]
@alliejanoch - amazing, thank you!!! Sorry to not reply to your previous message - I did actually start working on a pull request but then switched off my laptop and by the morning had forgotten all about it...
Thanks again!

**Comment by alliejanoch** [comment]
@philmcmahon - I've done a few more updates. Version 2.0.0 is a breaking change, but you can now initialize the module in one of two ways:

``` js
var aws = require('aws-s3-promisified')();
```

or

``` js
var aws = require('aws-s3-promisified')({
    accessKeyId: AWS_ACCESS_KEY_ID,
    secretAccessKey: AWS_SECRET_ACCESS_KEY
});
```
