### ISSUE TITLE
Parameters access key id and secret key

### ISSUE THREAD

**Issue by mrn3** [Mapistry/awsS3Promisified#2]
Rather than setting environment variables AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, is there a way to pass them in as parameters?

**Comment by ssaunders** [comment]
From looking at the [code](https://github.com/Mapistry/awsS3Promisified/blob/master/index.js), it seems not. Though changing that would be easy. If you remove the parentheses on the last line, you can pass them as parameters to the initialize function. That means you have to initialize it, though.

```
//UNTESTED
var awsS3Promisified = {

  initialize: function(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY) {
  ...


};

module.exports = awsS3Promisified.initialize;   <<<<< like this
```

You may need to remove the parameters as well, in case there are conflicts.

**Comment by mrn3** [comment]
Great thanks!

**Comment by alliejanoch** [comment]
Hi @mrn3 - I just made a little update to make this easier. You should now be able to do:

``` js
var aws = require('aws-s3-promisified').initialize(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
```

**Comment by SamSamskies** [comment]
@alliejanoch I think you have a typo in that example. Shouldn't it be...

``` js
var aws = require('aws-s3-promisified').initialize(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
```

Also, I think what @ssaunders makes sense. It would be a little nicer to not have to explicitly call initialize. This would be a breaking change to the API though.

``` js
var aws = require('aws-s3-promisified')(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY);
```

**Comment by alliejanoch** [comment]
@mrn3 - I've released a new version of the library. This will break code that worked with previous versions. You can now initialize like this:

``` js
var aws = require('aws-s3-promisified')({
    accessKeyId: AWS_ACCESS_KEY_ID,
    secretAccessKey: AWS_SECRET_ACCESS_KEY
});
```

**Comment by mrn3** [comment]
Great thanks!
