### ISSUE TITLE
url expires in 8 hours.

### ISSUE THREAD

**Issue by ashrafkm** [Mapistry/awsS3Promisified#7]
Hi,
I am using `aws.getSignedURL(bucket, key);` to get image as url. But the url expires after 8 hours as mentioned in the librarry. So can we remove expiration?. can we make the url like no expiration. anytime client should able use it. is there possible?

I have tried here `setExpirationInSeconds(28800);` chaning the seconds  but still did not work.

**Comment by joeyshipley** [comment]
Sorry for the late response.

Looking into this some revealed that Amazon requires an Expires value be provided and that there is limitations to how long they can be. 

https://github.com/aws/aws-sdk-net/issues/528
